
backend:
  name: git-gateway
  repo: amine-benselim/nidhal-net
  branch: master

publish_mode: editorial_workflow
media_folder: "static/images" # Folder where user uploaded files should go

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/post"
    sort: "date:desc" # Default is title:asc
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Title, name: "title", widget: "string", tagname: "h1"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: Slug, name: "slug", widget: "string"}
      - {label: Tags, name: tags, widget: list}
      - {label: "Body", name: "body", widget: "markdown"}
